### ISSUE TITLE
Focus states for buttons

### ISSUE THREAD

**Issue by Magnus-G** [thoughtbot/bitters#104]
Should we include focus states for buttons and anchors? When tabbing through the Bitters example page the focus states for text anchors are very subtle and the "button anchors" don't have focus indications. 

We are currently setting `outline` to `none` here: https://github.com/thoughtbot/bitters/blob/master/app/assets/stylesheets/_typography.scss#L61

Should we consider not doing that?

**Comment by tysongach** [comment]
This good to close now, @kylefiedler?
