### ISSUE TITLE
Small numbers with font-feature-settings

### ISSUE THREAD

**Issue by microcipcip** [thoughtbot/bitters#130]
This mixin is making numbers very small (about half of the regular font size):
@include font-feature-settings("kern", "liga", "frac", "pnum");
After that I removed that line, they were looking fine again. What's the purpose of that mixin?

**Comment by abartlett57** [comment]
I ran across this issue on a project this week. It is related to "frac" and affects all numbers in all fonts (that support it)....BUT, it's only Windows8 specific. All browsers on any other system work fine, but all browsers on Win8 are affected. Just an FYI.

**Comment by tysongach** [comment]
We [removed `frac` from `font-feature-settings`](https://github.com/thoughtbot/bitters/commit/994b078d57ff8e351a88bd81f7dd07ba60068d2a#diff-956b372e3d32f4879e0e77e8cf8daa3cL2) in Bitters 1.0.0. You can carry over this small change to your project to fix this issue.
