### ISSUE TITLE
Using `figure` elements with `span-columns` mixin results in sadness 

### ISSUE THREAD

**Issue by zspencer** [thoughtbot/bitters#143]
It appears that mozilla and chrome both have a margin-before applied to figure elements. This causes the figure to take up a few ems more space than expected; breaking neat's grid :'(

A workaround is to remove the margin-before css attribute on all figures:
```
figure {
  -moz-margin-before: 0;
  -webkit-margin-before: 0;
  margin-before: 0;
}
```

I submitted [this issue to the neat team](https://github.com/thoughtbot/neat/issues/277#issuecomment-65448056) asking them where I should make a fix for this, and they told me to look to bitters. 

I'm planning to create an `_images.scss` and link that in to `_base`; but I don't quite have the time today to make that happen, so I'm creating an issue to stop in my personal to-do list. Expect a PR within the week.

If you have feedback on how you'd prefer I go about this, comments are more than welcome.

**Comment by kylefiedler** [comment]
@zspencer please add a PR

**Comment by tysongach** [comment]
These are browser defaults and I don’t think they should be part of Bitters. They are better served in a CSS reset, which we encourage to be used alongside Bitters.

I also believe you just need to set `margin: 0;` on `figure` elements and not `margin-before`.
