### ISSUE TITLE
Availability via NPM?

### ISSUE THREAD

**Issue by Mike-Loffland** [thoughtbot/bitters#146]
Can you guys throw a package.json file up so bitters can be accessed via NPM?

**Comment by bretthayes** [comment]
@Mike-Loffland I agree. This needs to be added. A **node-bitters** would be helpeful with Gulp support. However, I noticed a [bitter-orange](https://www.npmjs.com/package/bitter-orange) package that's being used by [node-bourbon](https://www.npmjs.com/package/node-bourbon) and [node-neat](https://www.npmjs.com/package/node-neat) as a dependent. Not sure if that will help you cause it didn't for me. There's no readme so I'm not sure how to implement it in my Gulp project.

**Comment by Mike-Loffland** [comment]
Thanks @bretthayes ... I'll give it a look.

**Comment by tysongach** [comment]
We don’t publish directly to npm because Bitters is meant to be installed locally in a project and its files are to be changed.

More info can be [found here](https://github.com/thoughtbot/bitters/pull/30).

**Comment by nodexp** [comment]
should anyway be there for getting started so anyone can include it in their package.json as a dependency and forget about it. Also if you want to extends bourbon or Bitters or whatever I imaging that in some way can be accomplished using pure sass. Then for customizations that are very tied to your project well then yes you should include the sources in your repo.
