### ISSUE TITLE
Select form

### ISSUE THREAD

**Issue by tomagladiator** [thoughtbot/bitters#158]
Hi,

Thanks for your work.

I wonder why the Select is not stylized (like an input with an arrow with width:100%) ?

Thanks

**Comment by tysongach** [comment]
Bitters is meant to help kick-off a project, so we aren’t implementing any custom styles for things like form elements (e.g. `select`).

That being said, this is just a starting point, so you can feel free to customize Bitters’ styles to fit your needs.

**Comment by tomagladiator** [comment]
Oh and I love this kick-off concept. :)
I was just surprise that all input form have style and not the select. So I add properties in my project to fit with the rest of the form. (border color, border radius, box shadow, padding, and width)
Thanks!
