### ISSUE TITLE
Inconsistent input size across browsers

### ISSUE THREAD

**Issue by tom--** [thoughtbot/bitters#159]
http://bitters.bourbon.io/example.html demonstrates.

The select, radio, checkbox and file input buttons are 16px in Firefox 36 and 13px in Chrome 41 and Safari 8.

**Comment by tysongach** [comment]
@tom-- Are you talking about the actual dimensions of these input elements? Here’s a screenshot from inspector in Firefox:

![ff-inputs](https://cloud.githubusercontent.com/assets/903327/6753540/1e4b4176-ceed-11e4-9c95-6f89527a7250.png)

If so, Bitters doesn’t adjust the sizing of these; they are browser defaults and each browser renders differently.

**Comment by tom--** [comment]
I was referring to

1. the computed value of `font-size`
1. how `font-size` inherits from `body` in FF and is set by Bitters' `_forms.scss` in Webkit
1. the appearance of the input elements relative to everything around them, in FF it looks reasonable, in Webkit the inputs look incongruously small relative to the labels

I imagined that Bitters would take care of this so that I don't need to. Bitters provides a typography with consistent sizes so I just assumed it would want to address this inconsistency too.   

![firefox](https://i.imgur.com/qsqxGR5.png)

![chrome](https://i.imgur.com/dO4cuRB.png)

**Comment by tysongach** [comment]
Bitters isn’t a reset, so I think this is outside the scope. These are just browsers computing the default size differently.
