### ISSUE TITLE
Webfont smoothing for FireFox

### ISSUE THREAD

**Issue by drtimofey** [thoughtbot/bitters#166]
In _typography.scss, it would probably make sense to include `-moz-osx-font-smoothing: grayscale;` right after `-webkit-font-smoothing: antialiased;`, to support FireFox.

Related: http://maximilianhoffmann.com/posts/better-font-rendering-on-osx & http://stackoverflow.com/questions/11459746

**Comment by whmii** [comment]
Actually, we are looking to remove all font smoothing. https://github.com/thoughtbot/bitters/pull/180 A lot of font smoothing options is dependent on a number of factors including what app you are using and the display your using is using to see the site. 

One of the bigger factors for bitters is that we don't know what fonts a designer/dev is going to want to use with their site. They may use a font that has good hinting so it is difficult to make blanket rules like 'all antialiased all the time'. For now we've decided to remove all smoothing.

@drtimofey let me know what you think.

**Comment by tysongach** [comment]
With #180 merged, can this be closed? Should we add `-moz-osx-font-smoothing` just to the button styles, as we do with `-webkit-font-smoothing`?

**Comment by whmii** [comment]
Closing
