### ISSUE TITLE
Remove Legacy reference to extends on example page.

### ISSUE THREAD

**Issue by whmii** [thoughtbot/bitters#168]

**Comment by whmii** [comment]
![screen shot 2015-04-27 at 9 55 15 am](https://cloud.githubusercontent.com/assets/2489247/7348930/87d2498e-ecc3-11e4-9b66-92b55365914b.png)

**Comment by tysongach** [comment]
These still exist: https://github.com/thoughtbot/bitters/blob/master/app/assets/stylesheets/_lists.scss

**Comment by whmii** [comment]
Gasp! mind blown

**Comment by cllns** [comment]
@tysongach Should this be opened again, due to #199? 

It doesn't need to happen yet, because they exist in the latest release (1.10), but before the next release would be great!

**Comment by whmii** [comment]
awe yea~~ :+1:
