### ISSUE TITLE
Ordered List (ol) is missing styling

### ISSUE THREAD

**Issue by drtimofey** [thoughtbot/bitters#169]
Bitters `&%default-ol` fails to take the "type" attribute into consideration.

Ordered list have an attribute called "type", which controls the bullet point style, i.e. roman numerals, letters, etc..., see more http://www.w3schools.com/cssref/pr_list-style-type.asp

`&%default-ol` needs to have something along these lines:

    &%default-ol {
        list-style-type: decimal;
        margin-bottom: $small-spacing;
        padding-left: $base-spacing;
        &[type=a] {
          list-style-type: lower-alpha;
        }
        &[type=A] {
          list-style-type: upper-alpha;
        }
        &[type=i] {
          list-style-type: lower-roman;
        }
        &[type=I] {
          list-style-type: upper-roman;
        }
    }

**Comment by drtimofey** [comment]
There is only one issue with the proposed solution... Attribute selectors are not case sensitive, so `<ol type="a">` will be treated as `<ol type="A">`. See http://stackoverflow.com/questions/27104096

Maybe instead add more extenders, such as:

    &%default-ol,
    &%default-ol-1 {
        list-style-type: decimal;
        margin-bottom: $small-spacing;
        padding-left: $base-spacing;
    }
  
    &%default-ol-a {
        list-style-type: lower-alpha;
        margin-bottom: $small-spacing;
        padding-left: $base-spacing;
    }
  
    &%default-ol-A {
        list-style-type: upper-alpha;
        margin-bottom: $small-spacing;
        padding-left: $base-spacing;
    }
  
    &%default-ol-i {
        list-style-type: lower-roman;
        margin-bottom: $small-spacing;
        padding-left: $base-spacing;
    }
  
    &%default-ol-I {
        list-style-type: upper-roman;
        margin-bottom: $small-spacing;
        padding-left: $base-spacing;
    }

**Comment by tysongach** [comment]
@drtimofey Is there a particular reason you’re using these attributes rather than styling via CSS’s `list-style-type`?

[MDN notes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol#Attributes):

> Unless the value of the list number matters (e.g. in legal or technical documents where items are to be referenced by their number/letter), the CSS list-style-type property should be used instead.

I think for the purpose of Bitters, we would always recommend—and most commonly use—using CSS to style, rather than use these HTML attributes.

**Comment by drtimofey** [comment]
@tysongach, you're right! I'm closing the issue!
