### ISSUE TITLE
Curious at list styles

### ISSUE THREAD

**Issue by nikolasleblanc** [thoughtbot/bitters#170]
Hey guys, just wondering why your default rendering of ordered and unordered lists is to eliminate their visual "listiness" entirely. Is that a design decision?

![bitters_-_example](https://cloud.githubusercontent.com/assets/1944954/7463025/1a506014-f284-11e4-82af-66c3c892c889.jpg)

**Comment by tysongach** [comment]
In the context of user interfaces, we like to begin with a baseline—no list styles—and then use a component-based approach to change styling depending on the purpose.
