### ISSUE TITLE
Re-add focus outline on anchors

### ISSUE THREAD

**Issue by derekprior** [thoughtbot/bitters#172]
[This commit](https://github.com/thoughtbot/bitters/commit/469b3b81d963387db6a47e81cbe6f5f2045fc5ba) removed focus outlines on anchors. Is there a compelling reason to do this?

I think it's common to forget to also style `:focus` when styling `:hover`. Combine that with `:hover` often being a very subtle effect and I think we're likely to end up in a situation where it's not always clear what element has keyboard focus.

Focus indication seems like something that people who need tab-based navigation can't use your site without. Meanwhile, your mouse-using users are unlikely to ever even see the indication on links, which is fine; they don't need it. What do you think about re-adding the default outline?

**Comment by elomatreb** [comment]
My (personal) problem with relying on the default focus outline is the inconsistency. It looks different in every browser and/or OS. Some brothers show the focus styling when a link/button is pressed, others don't. (Just my 2ct)

**Comment by tysongach** [comment]
Yeah, the look-and-feel of default `:focus` styling is such a bummer. _But_, I do agree that we should provide a better indication of `:focus` than what we do now.

**Comment by ckundo** [comment]
@derekprior you're right, folks who have motor impairments may use keyboard nav or switches to navigate content, and without indication of focus it's very difficult or impossible to use an application.

> Meanwhile, your mouse-using users are unlikely to ever even see the indication on links

Clicks do trigger visible outline by default, so browsers will show the outline on control activation. This is probably why the outline was removed to begin with. However, we might try `a:active {outline:none;}` to remove the outline just for mouse clicks. http://www.456bereastreet.com/archive/200910/remove_the_outline_from_links_on_active_only/

**Comment by joe-watkins** [comment]
Hi :) @ckundo brought this issue to my attention and thought I should maybe chime in as an accessibility advocate/geek.

Firstly, Chrome is a big offender of :focus state on clicks... there is an open bug that they are addressing soon I believe. Browsers all behave a bit differently in this regard unfortunately.

I find it's good practice to let authors make poor accessibility decisions like outline:none; Of most site's I audit for accessibility this is the #1 fail. Setting up framework users for #a11y success out of the gate is a huge win for a framework and the web.

I'd suggest offering up special accessibility notes in documentation showing examples of using outline: none; with good CSS borders/backgrounds for :focus state as alternatives. UK.gov nails this approach perfectly: https://www.gov.uk/

Bootstrap does an good job with making accessibility concern notes in there docs and they provide code examples w/a11y in mind.

**Comment by elomatreb** [comment]
@ckundo Chromium (And maybe some other webkit browsers) do not show the outline (on links, at least) when clicking.

**Comment by ckundo** [comment]
Created a PR #174, we can continue discussion there.
