### ISSUE TITLE
Install via bower?

### ISSUE THREAD

**Issue by stepmr** [thoughtbot/bitters#186]
Hi guys,
in adding a a bower install like Bourbon and Neat?

**Comment by tysongach** [comment]
Hi!

We don’t publish Bitters on Bower for reasons explained [here](https://github.com/thoughtbot/bitters/pull/105) and [here](https://github.com/thoughtbot/bitters/pull/173).

**Comment by helgatheviking** [comment]
+1 I'd have liked it to be installable via bower too. That leaves it up to us to decide how we wanted to use it in our projects.
