### ISSUE TITLE
Odd rendering of numbers on the example page

### ISSUE THREAD

**Issue by MichaelThessel** [thoughtbot/bitters#187]
The [example page](http://bitters.bourbon.io/example.html) seems to render all numbers in a subscript style. Tested in recent FF & Chrome.

![image](https://cloud.githubusercontent.com/assets/2926266/8884284/6534dfd6-320a-11e5-97b3-876809010e9d.png)

**Comment by whmii** [comment]
Hmm, looks like a quirk of `font-feature-settings`.

I'll look in to it. Thanks for the heads up.

https://github.com/thoughtbot/bitters/blob/master/app/assets/stylesheets/_typography.scss#L4

**Comment by whmii** [comment]
I have been unable to recreate this issue. Closing (for now)

**Comment by MichaelThessel** [comment]
Still looks like this for me in Chrome.
