### ISSUE TITLE
Compatibility with Bourbon 5

### ISSUE THREAD

**Issue by mindeavor** [thoughtbot/bitters#194]
I just installed bourbon 5, neat, and bitter `1.0.0`. Here's what I had to fix to get everything to compile:

`_buttons.scss`

- Change `$all-button-inputs` to `$all-buttons`
- Change `@include appearance(none);` to `appearance: none;`

`_tables.scss`

- Change `@include font-feature-settings("kern", "liga", "tnum")` to `font-feature-settings: "kern", "liga", "tnum"`
- Change `@include font-feature-settings("kern", "liga", "pnum")` to `font-feature-settings: "kern", "liga", "pnum"`

**Comment by tysongach** [comment]
Yep, that sounds about right. The `master` branch is actually already compatible with Bourbon 5, but we haven’t cut a public release yet. Hope to do that soon.

cc: @whmii

**Comment by tysongach** [comment]
@mindeavor We just released [Bitters 1.1](https://github.com/thoughtbot/bitters/releases/tag/v1.0.0) which is compatible with Bourbon 5.0.

**Comment by mindeavor** [comment]
Great! :D

**Comment by alokamme** [comment]
Its not working.
 ERROR - Undefined variable: "$all-buttons" also 
i'm using bourbon 5.0.0.beta.8, neat-2.1.0, bitters-1.5.0
Before that i was getting Undefined variable: "$font-stack-system"
then i changed $base-font-family: $font-stack-system; to $base-font-family: "Ubuntu", sans-serif; now I'm getting this error. I gone through all the resources but nothing worked.
