### ISSUE TITLE
Website instructions

### ISSUE THREAD

**Issue by spyridonas** [thoughtbot/bitters#196]
Website http://bitters.bourbon.io/ says " Import Bitters after Bourbon and Neat in your application.css.scss".

Github says " import Neat after Bitters in your application.css.scss"

**Comment by whmii** [comment]
fixed https://github.com/thoughtbot/bitters/pull/203

**Comment by tysongach** [comment]
@whmii This issue is in regard to the website, not the readme: http://bitters.bourbon.io

**Comment by tysongach** [comment]
Closed via https://github.com/thoughtbot/bitters/commit/3877e30bf315efe0a00c322d494578b3e8e957ea.
