### ISSUE TITLE
Please add docs for Bitters, thanks!

### ISSUE THREAD

**Issue by Hongbo-Miao** [thoughtbot/bitters#205]
Both Bourbon and Neat have docs that help us easy to learn and use. And I love them.
http://bourbon.io/docs/
http://thoughtbot.github.io/neat-docs/latest/

But when I try to use Bitters, I cannot find any document or example related to it. Can you add it? Thanks!

**Comment by tysongach** [comment]
@Hongbo-Miao Since Bitters is a set of base styles, there really isn’t anything to “document” like Bourbon and Neat. It’s all just standard CSS; a starting point or scaffold. That being said, our from of “documentation” is our Example page: http://bitters.bourbon.io/example.html

**Comment by Hongbo-Miao** [comment]
@tysongach got it, thanks for help!
