### ISSUE TITLE
Gulpfile needs multiple sass paths

### ISSUE THREAD

**Issue by whmii** [thoughtbot/bitters#207]
https://github.com/thoughtbot/bitters/blob/master/Gulpfile.js#L7 should read as follows. 
```js
var paths = {
  scss: [
    "./app/assets/stylesheets/**/*.scss",
    "./contrib/*.scss"
  ]
};
```

**Comment by tysongach** [comment]
Why? Isn’t the contrib Sass just importing all of the Bitters partials?

**Comment by whmii** [comment]
Yea, but if effect the `watch` method. Otherwise the repo will not correctly recompile after changes
