### ISSUE TITLE
ruby 2.3.0

### ISSUE THREAD

**Issue by kvokka** [thoughtbot/bitters#215]
```
kvokka@kvokka-PC:~/proj/my3$ bitters install --path app/assets/stylesheets from
/home/kvokka/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x11be7d8 bitters-1.2.0> (NoMethodError)
        from /home/kvokka/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
        from /home/kvokka/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
        from /home/kvokka/.rvm/gems/ruby-2.3.0/gems/bitters-1.2.0/lib/bitters.rb:1:in `<top (required)>'
        from /home/kvokka/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /home/kvokka/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from /home/kvokka/.rvm/gems/ruby-2.3.0/gems/bitters-1.2.0/bin/bitters:3:in `<top (required)>'
        from /home/kvokka/.rvm/gems/ruby-2.3.0/bin/bitters:23:in `load'
        from /home/kvokka/.rvm/gems/ruby-2.3.0/bin/bitters:23:in `<main>'
        from /home/kvokka/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/kvokka/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by tysongach** [comment]
Hi @kvokka! Are you still having issues?

I’m not using rvm (I use rbenv), but I don’t seem to be able to replicate the issues. It works as expected (with Ruby 2.3.0 and Bitters 1.2):

![screen shot 2016-01-20 at 11 42 55](https://cloud.githubusercontent.com/assets/903327/12455807/1ad49082-bf6b-11e5-9287-97ff15888431.png)

**Comment by fatroller** [comment]
Yes, I'm getting the same error while running a rubber -h command. I'm using rvm on Mac OS X 10.11.2.

Any assistance would be appreciated ?

$ rubber -h
/Users/gauravsarin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fd0a6037e2c rubber-3.2.0> (NoMethodError)
	from /Users/gauravsarin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/gauravsarin/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/gauravsarin/.rvm/gems/ruby-2.3.0@newapp/gems/rubber-3.2.0/bin/rubber:13:in `<top (required)>'
	from /Users/gauravsarin/.rvm/gems/ruby-2.3.0@newapp/bin/rubber:23:in `load'
	from /Users/gauravsarin/.rvm/gems/ruby-2.3.0@newapp/bin/rubber:23:in `<main>'
	from /Users/gauravsarin/.rvm/gems/ruby-2.3.0@newapp/bin/ruby_executable_hooks:15:in `eval'
	from /Users/gauravsarin/.rvm/gems/ruby-2.3.0@newapp/bin/ruby_executable_hooks:15:in `<main>'

**Comment by magikid** [comment]
I'm also having this issue.  After some research, it's an [issue with RubyGems](https://github.com/rubygems/rubygems/issues/1420).

There is a quick fix from @tenderlove that solves it for me:

```diff
diff --git a/lib/rubygems/specification.rb b/lib/rubygems/specification.rb
index 726d301..a010bb0 100644
--- a/lib/rubygems/specification.rb
+++ b/lib/rubygems/specification.rb
@@ -2999,6 +2999,8 @@ open-ended dependency on #{dep} is not recommended

   extend Gem::Deprecate

+  def this; self; end
+
   # TODO:
   # deprecate :has_rdoc,            :none,       2011, 10
   # deprecate :has_rdoc?,           :none,       2011, 10
```

**Comment by tysongach** [comment]
Closing, as we’re unable to replicate and appears to be an issue with either your local dev environment or RubyGems.

**Comment by thebadmonkeydev** [comment]
For anyone who stumbles on this like I did...if you're using RVM, I was able to get up and running by reinstalling Ruby: `rvm reinstall 2.3.0`

**Comment by petercunning** [comment]
rvm reinstall 2.3.0 worked for me.. Thanks !

**Comment by jamiefolsom** [comment]
Issue with rubygems is fixed in v. 2.6.3, released yesterday. See: https://github.com/rubygems/rubygems/issues/1420
