### ISSUE TITLE
Remove old features from the website

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/bitters#216]
Remove mention of `%default-ul` and `%default-ol`, which [no longer exist](https://github.com/thoughtbot/bitters/commit/e2195a15e86765f2bdcc4e61c18a67e253edc788).

**Comment by riddley** [comment]
The homepage currently links to several 404s as well.

**Comment by coreyzev** [comment]
Commit aa84e60 seems to have fixed it for branch: `gh-pages` but not for the repo & README.md

see: https://github.com/thoughtbot/bitters/issues/253
