### ISSUE TITLE
line-height missing em 

### ISSUE THREAD

**Issue by jjmulenex** [thoughtbot/bitters#221]
So the processed css is missing the "em" for the default processed bitters scss

example: 
body {
  color: #333;
  font-family: "Helvetica Neue", "Helvetica", "Roboto", "Arial", sans-serif;
  font-size: 1em;
  line-height: 1.5; }

I have attached the css generated. 
[app copy.css.txt](https://github.com/thoughtbot/bitters/files/133313/app.copy.css.txt)

Thanks
Jeremy

**Comment by whmii** [comment]
This is intended. `line-height` does not require a unit (and it is generally preferred to not have one).

See: https://developer.mozilla.org/en-US/docs/Web/CSS/line-height#Prefer_unitless_numbers_for_line-height_values

**Comment by poedenon** [comment]
interesting when setting em as a value type there is a huge difference in
display. So when using refills with the article snippets and dropping the
the "em" the trailing carrot drops below the base line. [image: Screen Shot
2016-02-16 at 3.48.29 PM.png]
I can load the site so you can see the problem across your products, which
I love btw.

thanks
Jeremy

**Comment by poedenon** [comment]
after reading: https://css-tricks.com/almanac/properties/l/line-height/ I
see what you were intending. I guess the override is refills needs to be
more specific.

thanks again.
jeremy

**Comment by tysongach** [comment]
@poedenon I don’t think your screenshot made it to GitHub, can you re-post so we have a better sense of the issue?

If Refills is using a unit in `line-height` values, that’s a bug and we should probably remove those.

**Comment by poedenon** [comment]
Here is the screenshot

<img width="1095" alt="screen shot 2016-02-16 at 3 48 29 pm" src="https://cloud.githubusercontent.com/assets/3333209/13099266/3eabe744-d4f6-11e5-8598-f2369cd192d9.png">

**Comment by whmii** [comment]
@jjmulenex Yep, it also looks like the "Read More >" is `display: inline-block` and not just `display: inline`. You may have better luck just trying `display: inline` on the link. Alternatively you can mess with `vertical-align: baseline` which should be.

**Comment by whmii** [comment]
seems resolved. reopen if issue is continued
