### ISSUE TITLE
Cannot use after install

### ISSUE THREAD

**Issue by jamierocks** [thoughtbot/bitters#228]
It seems to not be added to the path after ```gem install bitters```.

```bash
jamie@Jamies-Mac-mini  ~/proj/lexteam/site/indigo/src/scss   master ●  bitters install
zsh: command not found: bitters
```

OS: OS X

**Comment by tysongach** [comment]
@jamierocks We think we tracked the problem down and I just cut a release with a fix. Can you install Bitters `1.3.1` and see if this issue is resolved?
