### ISSUE TITLE
Undefined variable: "$font-stack-system"

### ISSUE THREAD

**Issue by rostixman** [thoughtbot/bitters#234]
hello everyone
i have problem:

**my application.scss:**
@import "portlets/variables";
@import "../_sass/bourbon/bourbon";
@import "../_sass/base/base";
@import "../_sass/neat/neat";
@import "portlets/custom";

**gems:**
gem 'bourbon'
gem 'neat'
gem 'bitters'

**versions:**
Using bourbon 5.0.0.beta.3
Using neat 1.7.4
Using bitters 1.3.1

**after run server i look at this error:**
Undefined variable: "$font-stack-system"

**Comment by rostixman** [comment]
i change gem 'bourbon', '= 4.2.6' and have new error:
Undefined variable: "$helvetica"

**Comment by tysongach** [comment]
@rostixman Hi! In Bourbon 5, font stack variables have been renamed. So, `$helvetica` is now `$font-stack-helvetica`, etc. We also have some new ones, including the `$font-stack-system` you mention above; Bitters `1.3.1` ships with this being called.

That being said, Bourbon `4.2.6` still include `$helvetica` and that should work fine. You could possibly have a caching issue after switching gem versions. Can you clear that and see if it helps?

Finally, I’m assuming this is a Rails app? Is it a new one, or an existing app? I noticed you have `gem "bitters"` listed above, and I wanted to note that you should install the Bitters files _locally_ into your `stylesheets` directory, rather than through a gem in your Gemfile. This is because Bitters is not a library, but a scaffold and the files are expected to be changed and updated over time. We also rapidly develop and introduce breaking changes to Bitters, so suddenly upgrading a Bitters instance in a project is not recommended.

**Comment by rostixman** [comment]
@tysongach thank you for your help. I tried to delete gems (bourbon, neat, bitters) and restart rails server, but problem remained the same O_o. After that I tried to clear cache (rake assets:clean), but nothing has changed. I'm very surprised and I don't know how to fix it? Can you help me, please :)

**Comment by tysongach** [comment]
@rostixman Is this code open-source somewhere that I can see it? Or, can you paste your Gemfile.lock and your Sass manifest file?

**Comment by rostixman** [comment]
@tysongach this is my gemfile.lock

`GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.5.1)
      actionpack (= 4.2.5.1)
      actionview (= 4.2.5.1)
      activejob (= 4.2.5.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.5.1)
      actionview (= 4.2.5.1)
      activesupport (= 4.2.5.1)
      rack (~> 1.6)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (4.2.5.1)
      activesupport (= 4.2.5.1)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    activejob (4.2.5.1)
      activesupport (= 4.2.5.1)
      globalid (>= 0.3.0)
    activemodel (4.2.5.1)
      activesupport (= 4.2.5.1)
      builder (~> 3.1)
    activerecord (4.2.5.1)
      activemodel (= 4.2.5.1)
      activesupport (= 4.2.5.1)
      arel (~> 6.0)
    activesupport (4.2.5.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    arel (6.0.3)
    babel-source (5.8.35)
    babel-transpiler (0.7.0)
      babel-source (>= 4.0, < 6)
      execjs (~> 2.0)
    bcrypt (3.1.11)
    better_errors (2.1.1)
      coderay (>= 1.0.0)
      erubis (>= 2.6.6)
      rack (>= 0.9.0)
    binding_of_caller (0.7.2)
      debug_inspector (>= 0.0.1)
    bourbon (4.2.6)
      sass (~> 3.4)
      thor (~> 0.19)
    browserify-rails (1.5.0)
      railties (>= 4.0.0, < 5.0)
      sprockets (> 3.0.2)
      tilt (>= 1.1, < 3)
    builder (3.2.2)
    byebug (8.2.2)
    coderay (1.1.1)
    coffee-rails (4.1.1)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0, < 5.1.x)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    concurrent-ruby (1.0.1)
    connection_pool (2.2.0)
    daemons (1.2.3)
    debug_inspector (0.0.2)
    devise (3.5.6)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
    erubis (2.7.0)
    eventmachine (1.0.9.1)
    execjs (2.6.0)
    globalid (0.3.6)
      activesupport (>= 4.1.0)
    i18n (0.7.0)
    jbuilder (2.4.1)
      activesupport (>= 3.0.0, < 5.1)
      multi_json (~> 1.2)
    json (1.8.3)
    loofah (2.0.3)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mailcatcher (0.6.4)
      activesupport (~> 4.0)
      eventmachine (= 1.0.9.1)
      mail (~> 2.3)
      rack (~> 1.5)
      sinatra (~> 1.2)
      skinny (~> 0.2.3)
      sqlite3 (~> 1.3)
      thin (~> 1.5.0)
    mime-types (2.99.1)
    mini_portile2 (2.0.0)
    minitest (5.8.4)
    multi_json (1.11.2)
    neat (1.7.4)
      bourbon (>= 4.0)
      sass (>= 3.3)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    orm_adapter (0.5.0)
    pg (0.18.4)
    quiet_assets (1.1.0)
      railties (>= 3.1, < 5.0)
    rack (1.6.4)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (4.2.5.1)
      actionmailer (= 4.2.5.1)
      actionpack (= 4.2.5.1)
      actionview (= 4.2.5.1)
      activejob (= 4.2.5.1)
      activemodel (= 4.2.5.1)
      activerecord (= 4.2.5.1)
      activesupport (= 4.2.5.1)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.5.1)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.7)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.3)
      loofah (~> 2.0)
    rails-i18n (4.0.8)
      i18n (~> 0.7)
      railties (~> 4.0)
    railties (4.2.5.1)
      actionpack (= 4.2.5.1)
      activesupport (= 4.2.5.1)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.5.0)
    react-rails (1.6.2)
      babel-transpiler (>= 0.7.0)
      coffee-script-source (~> 1.8)
      connection_pool
      execjs
      rails (>= 3.2)
      tilt
    responders (2.1.1)
      railties (>= 4.2.0, < 5.1)
    sass (3.4.21)
    sass-rails (5.0.4)
      railties (>= 4.0.0, < 5.0)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    sinatra (1.4.7)
      rack (~> 1.5)
      rack-protection (~> 1.4)
      tilt (>= 1.3, < 3)
    skinny (0.2.4)
      eventmachine (~> 1.0.0)
      thin (>= 1.5, < 1.7)
    slim (3.0.6)
      temple (~> 0.7.3)
      tilt (>= 1.3.3, < 2.1)
    spring (1.6.4)
    sprockets (3.5.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.0.4)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    sqlite3 (1.3.11)
    temple (0.7.6)
    thin (1.5.1)
      daemons (>= 1.0.9)
      eventmachine (>= 0.12.6)
      rack (>= 1.0.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (2.0.2)
    translit (0.1.5)
    turbolinks (2.5.3)
      coffee-rails
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    warden (1.2.6)
      rack (>= 1.0)

PLATFORMS
  ruby

DEPENDENCIES
  better_errors
  binding_of_caller
  bourbon (= 4.2.6)
  browserify-rails (~> 1.5.0)
  byebug
  devise
  jbuilder (~> 2.0)
  mailcatcher
  neat
  pg (~> 0.15)
  quiet_assets
  rails (= 4.2.5.1)
  rails-i18n
  react-rails (~> 1.6.0)
  sass-rails
  slim
  spring
  translit
  turbolinks
  uglifier (>= 1.3.0)

BUNDLED WITH
   1.11.2
`
I found issue https://github.com/thoughtbot/bourbon/issues/120 and my problem is exactly the same.

When server was running I added gems bourbon and neat everything was normal. After bundle update I got 

**"File to import not found or unreadable: bourbon." **

and after that I restarted server and got 

**"Undefined mixin 'outer-container'."**

then I found this help page https://github.com/thoughtbot/bourbon/wiki/Rails-Help-%5C-Undefined-mixin and tried to do it step by step, but when I commented my mixin I got 

**"Undefined variable: "$helvetica""**

I've uncommented my mixin and now I try to think how to fix it.

This is my structure stylesheets folder:

`admin
-- portlets 
-- -- _custom.scss
-- -- _gridlove.scss
-- application.css.scss
bitters
-- _base.scss
-- _buttons.scss
-- _forms.scss
-- _grid-settings.scss
-- _lists.scss
-- _tables.scss
-- _typography.scss
-- _variables.scss`

custom.scss:
`header {
	@include outer-container;

	.logo {
		@include span-columns(3);
	}
	.user {
		@include shift(9);
		@include span-columns(4);
	}
}`

applications.scss:
`@import "bourbon";
@import "neat";
@import "../bitters/base";
@import "portlets/gridlove";
@import "portlets/custom";`

**Comment by tysongach** [comment]
@rostixman Your `Gemfile.lock` looks good, as well as your Sass manifest.

Is your `application.css.scss` not in the root of `stylesheets`? Rather it’s nested within `admin/`? Any reason for this?

**Comment by rostixman** [comment]
@tysongach I have 2 namespace: `admin`, `site`. I think it's a good idea to put all site stylesheets to folder `stylesheets/site` and admin stylesheets to `stylesheets/admin`. Is it a mistake?

**Comment by tysongach** [comment]
@rostixman Are you able to share the project’s source code with me? I’m not sure I’ll be able to debug much more without having the codebase to reference.

**Comment by rostixman** [comment]
@tysongach my project https://bitbucket.org/rostixman/rostixman-web

**Comment by tysongach** [comment]
@rostixman Thanks! Huge help.

It looks like the issue is that you have Sprockets directives (for example `*= require_tree ../`) in `app / assets / stylesheets / site / application.css`. If you remove all of these, the error you’re seeing should go away. Instead of Sprockets, you can just keep using Sass imports for everything.

**Comment by rostixman** [comment]
@tysongach impossible! it really works. I'm very surprised. I thought that if I divide site stylesheets and admin stylesheets, site application.css will not interfere normal work of admin/application.scss.

Thank you for help very much!

**Comment by bulletprince** [comment]
Just make some changes in base folders that gets created after you install bitters. Goto _variable.scss
copy and paste the following code under //Typography
// Typography
$sans-serif: $monospace;
$serif: $georgia;

$base-font-family: $sans-serif;
$heading-font-family: $base-font-family;
