### ISSUE TITLE
Also receiving error: Undefined variable: "$font-stack-system" 

### ISSUE THREAD

**Issue by CTMediaStudio** [thoughtbot/bitters#235]
I'm rather new to using Bourbon, Neat and Bitters but I seem to be having a similar issue with a non rails app. Just a regular old WordPress theme I'm working on from scratch. I'm using CodeKit to watch/compile my Sass. 

These versions are installed locally in a 'sass' folder located in my wp-content/themes/my_theme_name folder.

Bourbon 4.2.6
Neat 1.7.2
Bitters 1.3.1

The sass folder contains 4 folders currently that are bourbon, neat, base, and partials. style.scss is in the root. The top of style.scss that compiles to my theme's style.css file looks as follows:

// Reset
@import 'partials/reset'; 

// Bourbon & Neat & Bitters

@import 'bourbon/bourbon';
@import 'neat/neat';
//@import 'base/base';

If the base import is uncommented I receive that error which then throws an error in _base.scss and _style.scss too though it originates in _variables.scss

**Comment by tysongach** [comment]
@CTMediaStudio Hi! Bitters `1.3` [requires Bourbon `5.0`](https://github.com/thoughtbot/bitters#requirements). You can either upgrade Bourbon to `5.0`, or downgrade Bitters to `1.2`.

**Comment by smth** [comment]
It would be good if the default / stable versions of Bourbon and Bitter were compatible ;) i.e you should probably change Bitters version to reflect https://github.com/thoughtbot/bourbon/issues/874
