### ISSUE TITLE
ActionView::Template::Error (Undefined variable: "$helvetica".

### ISSUE THREAD

**Issue by qrush** [thoughtbot/bitters#24]
Got this off a fresh Rails 4.0 install, after installing and importing bitters:

```
ActionView::Template::Error (Undefined variable: "$helvetica".
  (in /Users/qrush/Dev/switchboard/app/assets/stylesheets/application.css.scss:3)):
    2: <html>
    3: <head>
    4:   <title>Switchboard</title>
    5:   <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    6:   <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    7:   <%= csrf_meta_tags %>
    8: </head>
```

Found that this is in Bourbon...so installing that now. I thought I wouldn't have to, since the README says:

> Install Bourbon and Neat (optional).

So maybe that means Install Bourbon, OPTIONALLY install Neat? Maybe this just needs to be clarified in the README.

**Comment by EllieMcGregor** [comment]
You have to remove the require tree sprocket from your application.css.scss
