### ISSUE TITLE
bitters install --> command not found

### ISSUE THREAD

**Issue by joshuaward** [thoughtbot/bitters#244]
Trying to install bitters in a new directory but I get the error:

![screen shot 2016-05-27 at 11 20 51](https://cloud.githubusercontent.com/assets/2747714/15615719/223c0944-23fd-11e6-87f7-775901c615b6.png)

I have Bitters 1.2.0 Gem installed. Not sure how to get it working.

Any suggestions would be greatly appreciated :) Love the framework!

**Comment by gffuentes** [comment]
hi joshua - i was able to get this to install so i think i may be able to help if this is something you are still working on. Is this a rails app you are trying to style? did you get stuck on any of the steps installing bourbon?

**Comment by whmii** [comment]
@joshuaward you may need to make sure you have it installed globally. That would be my only guess. I am going to close this issue for now but feel free to reopen if the issue persists.
