### ISSUE TITLE
`@extend %default-ul;` isn't working for me.

### ISSUE THREAD

**Issue by coreyzev** [thoughtbot/bitters#253]
I definitely have bourbon imported, and I'm calling it after my bitters is called. 

index.scss: 
```
@import "bourbon";
@import "base/base";
@import "neat";

@import "mySass";
```

in *_mySass.scss* I add:
```
ul {
    @extend %default-ul;
}
```

And I get this error:
```
>> Error: ".activity-details-col ul" failed to @extend "%default-ul".
>>        The selector "%default-ul" was not found.
>>        Use "@extend %default-ul !optional" if the extend should be able to fail.
>>         on line 28 of app/styles/seller/activity/_details.scss
>> >>         @extend %default-ul;
>>    --------^
```

I cannot find `%default-ul` anywhere in my code, or anywhere in this repo, so I dont even know where it would extend from. 

I am assuming somehow recently it got left out of a build? Or am I doing something wrong?

**Comment by tysongach** [comment]
Hi @coreyzev!

Apologies for the confusion. The `%default-ul` and `%default-ol` placeholder selectors were removed
in e2195a15e86765f2bdcc4e61c18a67e253edc788. Here’s the relevant PR for that, as well: https://github.com/thoughtbot/bitters/pull/199

We forgot to remove the mention of these from the readme, though. I’ll have a PR up shortly to fix that.
