### ISSUE TITLE
Remove named color from form placeholder property

### ISSUE THREAD

**Issue by whmii** [thoughtbot/bitters#256]
#242 Introduced an issue of using named color variables (`$medium-gray`) outside of the variables file. This should instead be either:

1. its own variable like `$placeholder-color`
2. an adjustment of an existing color like `tint($base-font-color, 25%)`

**Comment by cappadona** [comment]
@whmii Happy to submit a PR once you and the team decide on a direction, if that helps.

**Comment by tysongach** [comment]
This was resolved in #257 and has been released as part of Bitters 1.4.
