### ISSUE TITLE
Do we have a version that works with bourbon 4.27

### ISSUE THREAD

**Issue by weareREASON** [thoughtbot/bitters#278]
just seeing if we can install an older version that will work with bourbon 4.2.7
Seemed to get a few errors installing the latest version with this version of bourbon

**Comment by tysongach** [comment]
Yes, v1.2 is compatible with Bourbon v4.2.7: https://github.com/thoughtbot/bitters/releases/tag/v1.2.0.

**Comment by weareREASON** [comment]
because I installed the newer version - does that mean that it has also installed the newer version of bourbon ??

**Comment by tysongach** [comment]
@weareREASON That depends. Are you managing dependencies through a Gemfile? Did you install Bitters through our CLI? Something else?

**Comment by weareREASON** [comment]
OS Terminal

**Comment by tysongach** [comment]
You can run `bitters -v` and `bourbon -v` you see what versions you have installed.

Using our CLI, when you run `bitters install`, it will install the latest version of the gem that you have on your machine. So, if you have Bitters 1.5 installed, you will need to remove that gem from your machine, and re-install an older version. You can do that by running `gem uninstall bitters` and then `gem install bitters -v 1.2.0`. Now running `bitters install` will install v1.2.0.
