### ISSUE TITLE
Change website to https://github.com/thoughtbot/bitters.bourbon.io

### ISSUE THREAD

**Issue by whmii** [thoughtbot/bitters#282]
Put together a new site. While it isn't "done" i think taking it live now would still be an improvement over the current site. Especially considering there is information on the live site that is just wrong.

![screencapture-bitters-netlify-1492547801684](https://cloud.githubusercontent.com/assets/2489247/25151885/38b155cc-2455-11e7-875e-e0816c194427.png)

**Comment by tysongach** [comment]
I do think it would be great to move to Middleman and Netlify, as we’ve done with Neat and Bourbon, but closing this for now until it’s a bit more actionable.
