### ISSUE TITLE
Local server to preview your changes

### ISSUE THREAD

**Issue by bryankang** [thoughtbot/bitters#289]
Instead of having to copying the [example](http://bitters.bourbon.io/example.html) to a separate page and applying styles to preview them, is there a way to start a local server using the `bitter` command? It would also watch for changes and apply them without having to reload the page.

I'm currently using gulp and browsersync to do this, but I have to remember to remove its reference for production.

**Comment by tysongach** [comment]
Hi @bryankang! We have [a simple HTML page](https://github.com/thoughtbot/bitters/blob/master/contrib/index.html) within this repo that pulls in Bitters’ styles, using [gulp to compile the Sass and run a preview server](https://github.com/thoughtbot/bitters/blob/master/Gulpfile.js). All of this is laid out in our [contributing documentation](https://github.com/thoughtbot/bitters/blob/master/CONTRIBUTING.md). Is this what you are looking for?

**Comment by tysongach** [comment]
Closing due to lack of response. Please re-open if we can help in any way!
