### ISSUE TITLE
NPM install missing from Installation instructions

### ISSUE THREAD

**Issue by erichiggins** [thoughtbot/bitters#298]
Other thoughtbot projects like bourbon and neat include instructions for how to install using the `npm` command, but bitters appears to be missing that from it's README, despite it being available in the npm registry under `bourbon-bitters`.

For folks like myself who don't use Ruby/Rails/gem, it'd be helpful to include these instructions consistently.

**Comment by tysongach** [comment]
Hi! We purposefully don't publish Bitters to npm on Bower because it's a scaffold, not a library. You can read more about that here: https://github.com/thoughtbot/bitters/pull/30
