### ISSUE TITLE
Fully remove bourbon as a dependency

### ISSUE THREAD

**Issue by composerinteralia** [thoughtbot/bitters#328]
https://github.com/thoughtbot/bitters/commit/e2303a11219d5eeb2db8351eb1baa1061efc17c7 removed bourbon as a dependency, but it still appears as a runtime dependency in the [gemspec](https://github.com/thoughtbot/bitters/blob/master/bitters.gemspec#L9). That line is preventing us from using bitters together with bourbon 6. Shall we remove it?

This came up in https://github.com/thoughtbot/suspenders/pull/987

**Comment by tysongach** [comment]
Huh…I didn’t realize we did that. I wish that would’ve gone through a PR.
